--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,4 +26,4 @@
           version: ${{ matrix.version }}
       - run: make test
         working-directory: none-ls.nvim
-        timeout-minutes: 1
+        timeout-minutes: 1